"""foto e solicitacoes de troca de email e cpf

Revision ID: 96f4ccdb1677
Revises: c4d8f2a6e1b3
Create Date: 2026-10-09 13:27:35.575040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f4ccdb1677'
down_revision: Union[str, None] = 'c4d8f2a6e1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes_alteracao',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('EMAIL', 'CPF', name='tipo_solicitacao'), nullable=False),
    sa.Column('valor_novo', sa.String(length=254), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO_EMAIL', 'PENDENTE', 'APROVADA', 'RECUSADA', 'CANCELADA', name='status_solicitacao'), nullable=False),
    sa.Column('email_confirmado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decidido_por_id', sa.UUID(), nullable=True),
    sa.Column('decidido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decidido_por_id'], ['usuarios.id'], name=op.f('fk_solicitacoes_alteracao_decidido_por_id_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_solicitacoes_alteracao_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solicitacoes_alteracao'))
    )
    op.create_index(op.f('ix_solicitacoes_alteracao_status'), 'solicitacoes_alteracao', ['status'], unique=False)
    op.create_index(op.f('ix_solicitacoes_alteracao_usuario_id'), 'solicitacoes_alteracao', ['usuario_id'], unique=False)
    op.create_index('uq_solicitacoes_alteracao_aberta', 'solicitacoes_alteracao', ['usuario_id', 'tipo'], unique=True, postgresql_where=sa.text("status IN ('AGUARDANDO_EMAIL', 'PENDENTE')"))
    op.create_table('tokens_troca_email',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('solicitacao_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_alteracao.id'], name=op.f('fk_tokens_troca_email_solicitacao_id_solicitacoes_alteracao'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_tokens_troca_email_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens_troca_email')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_tokens_troca_email_token_hash'))
    )
    op.create_index(op.f('ix_tokens_troca_email_usuario_id'), 'tokens_troca_email', ['usuario_id'], unique=False)
    op.add_column('usuarios', sa.Column('foto_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(op.f('uq_usuarios_foto_id'), 'usuarios', ['foto_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_usuarios_foto_id'), 'usuarios', type_='unique')
    op.drop_column('usuarios', 'foto_id')
    op.drop_index(op.f('ix_tokens_troca_email_usuario_id'), table_name='tokens_troca_email')
    op.drop_table('tokens_troca_email')
    op.drop_index('uq_solicitacoes_alteracao_aberta', table_name='solicitacoes_alteracao', postgresql_where=sa.text("status IN ('AGUARDANDO_EMAIL', 'PENDENTE')"))
    op.drop_index(op.f('ix_solicitacoes_alteracao_usuario_id'), table_name='solicitacoes_alteracao')
    op.drop_index(op.f('ix_solicitacoes_alteracao_status'), table_name='solicitacoes_alteracao')
    op.drop_table('solicitacoes_alteracao')
    sa.Enum(name='status_solicitacao').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='tipo_solicitacao').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
