"""data de nascimento do usuario

Revision ID: 4306855a73d9
Revises: 96f4ccdb1677
Create Date: 2026-10-09 14:17:26.172811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4306855a73d9'
down_revision: Union[str, None] = '96f4ccdb1677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Nula nas contas antigas; a idade é calculada a partir dela, não é guardada.
    # Nula nas contas antigas; a idade é calculada a partir dela, não é guardada.
    op.add_column('usuarios', sa.Column('data_nascimento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'data_nascimento')
    # ### end Alembic commands ###
